# Activar actualizaciones automáticas
auto-update: true
on-death:
  # empezar atrue, el jugador perderá una investigación aleatoria sobre la muerte.
  reset-random-research: true
  # Posibilidad de restablecer toda la investigación cuando el jugador muere(porcentaje)
  # Valores válidos: 0-100，empezar a100La investigación siempre se reiniciará.，0la investigación no se restablecerá
  chance-to-reset-all-researches: 5

on-research:
  # Probabilidad de fracaso de la investigación.(porcentaje)
  # Valores válidos: 0-100，empezar a100siempre falla，0no fallará
  chance-of-failure: 10

android:
  # Probabilidad de falla de la máquina(porcentaje)
  # Valores válidos: 0-100，empezar a100siempre se rompe，0no funcionará mal
  chance-to-malfunction: 10
  # Duración del fallo de la máquina(Segundo)
  malfunction-duration: 30

# Mensaje rápido
messages:
  # disponible %research% para mostrar los nombres de los estudios faltantes
  lost-random-research: '&cPerdiste una investigación desbloqueada!'
  lost-all-research: '&cOh, no!perdiste toda tu investigación!'
  research-failed: '&cInvestigación fallida! necesitas intentarlo de nuevo :^)'
  android-malfunctioned: '&cHay algo mal con tu robot! Volverá a funcionar después de un tiempo..'